import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "slick-carousel/slick/slick.css";
import "./globals.css";
import "@/styles/globals.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const CustomCursor = dynamic(
  () => {
    return import("@/components/CustomCursor");
  },
  { ssr: false }
);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className + "w-full"}
        
      >
        <Header />
        <CustomCursor />
        {children}
        <Footer />
      </body>
    </html>
  );
}
